apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-nats
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-nats
    spec:
      imagePullSecrets:
        - name: {{ $.Values.dockerPullSecret.name }}
      containers:
      - name: nats
        image: {{ .Values.nats.image }}
        args: ["-js", "--trace"]
        ports:
        - containerPort: 4222
        - containerPort: 6222
        - containerPort: 8222
