apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-nats
spec:
  selector:
    app: {{ $.Release.Name }}-nats
  ports:
  - name: client
    port: 4222
    targetPort: 4222
  - name: cluster
    port: 6222
    targetPort: 6222
  - name: monitor
    port: 8222
    targetPort: 8222
