apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-etcd
spec:
  selector:
    app: {{ $.Release.Name }}-etcd
  ports:
  - name: client
    port: 2379
    targetPort: 2379
  - name: peer
    port: 2380
    targetPort: 2380
