# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

policies:
  - name: "task_router"
    url: http://router-server:8000/v2/models/task_router_ensemble/infer
    llms:
      - name: Brainstorming
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: Chatbot
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: "Code Generation"
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: Summarization
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: "Text Generation"
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: "Open QA"
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: "Closed QA"
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: Classification
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: Extraction
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: Rewrite
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: Other
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: Unknown
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct

  - name: "complexity_router"
    url: http://router-server:8000/v2/models/complexity_router_ensemble/infer
    llms:
      - name: Creativity
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: Reasoning
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: "Contextual-Knowledge"
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: "Few-Shot"
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: "Domain-Knowledge"
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: "No-Label-Reason"
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct
      - name: Constraint
        api_base: http://llm-cluster-single.dynamo.svc.cluster.local:8080/v1
        api_key: ""
        model: llama-3.1-8b-instruct 